language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

services:
  - docker

branches:
only:
  - master

script:
  - nx test auth-service
  - nx test mail-service
  - nx test profile-service

after_success:
  - docker image build -t kwetter-auth-service -f auth-service.Dockerfile .
  - docker image build -t kwetter-mail-service -f mail-service.Dockerfile .
  - docker image build -t kwetter-profile-service -f profile-service.Dockerfile .

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: docker image push docker.io/$DOCKER_USERNAME/kwetter-profile-service

notifications:
  email: false
