language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

services:
  - docker

branches:
only:
  - master

script:
  - nx test auth-service
  - nx test mail-service
  - nx test profile-service

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
  # - docker image build -t $DOCKER_USERNAMEkwetter-auth-service -f kwetter-auth-service.Dockerfile .
  # - docker image build -t $DOCKER_USERNAME/kwetter-mail-service -f kwetter-mail-service.Dockerfile .
  - docker image build -t $DOCKER_USERNAME/kwetter-profile-service:latest -f kwetter-profile-service.Dockerfile .
  # - docker image push $DOCKER_USERNAME/kwetter-auth-service:latest
  # - docker image push $DOCKER_USERNAME/kwetter-mail-service:latest
  - docker image push $DOCKER_USERNAME/kwetter-profile-service:latest
